In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
path = 'Data/'

In [4]:
train = pd.read_csv(path+'Train.csv')
test = pd.read_csv(path+'Test.csv')
sub = pd.read_csv(path+'sample_submission.csv')

In [5]:
train.shape, test.shape

((33750, 15), (14454, 14))

In [151]:
train

,date_time,is_holiday,air_pollution_index,humidity,wind_speed,wind_direction,visibility_in_miles,dew_point,temperature,rain_p_h,snow_p_h,clouds_all,weather_type,weather_description,traffic_volume
0,2012-10-02 09:00:00,None,121,89,2,329,1,1,288.28,0.0,0.0,40,Clouds,scattered clouds,5545
1,2012-10-02 10:00:00,None,178,67,3,330,1,1,289.36,0.0,0.0,75,Clouds,broken clouds,4516
2,2012-10-02 11:00:00,None,113,66,3,329,2,2,289.58,0.0,0.0,90,Clouds,overcast clouds,4767
3,2012-10-02 12:00:00,None,20,66,3,329,5,5,290.13,0.0,0.0,90,Clouds,overcast clouds,5026
4,2012-10-02 13:00:00,None,281,65,3,329,7,7,291.14,0.0,0.0,75,Clouds,broken clouds,4918
5,2012-10-02 14:00:00,None,23,65,3,328,6,6,291.72,0.0,0.0,1,Clear,sky is clear,5181
6,2012-10-02 15:00:00,None,184,64,3,328,7,7,293.17,0.0,0.0,1,Clear,sky is clear,5584
7,2012-10-02 16:00:00,None,167,64,3,327,7,7,293.86,0.0,0.0,1,Clear,sky is clear,6015
8,2012-10-02 17:00:00,None,119,63,3,327,6,6,294.14,0.0,0.0,20,Clouds,few clouds,5791
9,2012-10-02 18:00:00,None,161,63,3,326,3,3,293.10,0.0,0.0,20,Clouds,few clouds,4770
10,2012-10-02 19:00:00,None,243,62,3,326,8,8,290.97,0.0,0.0,20,Clouds,few clouds,3539
11,2012-10-02 20:00:00,None,150,62,3,326,5,5,289.38,0.0,0.0,1,Clear,sky is clear,2784
12,2012-10-02 21:00:00,None,128,61,4,325,4,4,288.61,0.0,0.0,1,Clear,sky is clear,2361
13,2012-10-02 22:00:00,None,18,61,4,325,7,7,287.16,0.0,0.0,1,Clear,sky is clear,1529
14,2012-10-02 23:00:00,None,186,60,4,324,5,5,285.45,0.0,0.0,1,Clear,sky is clear,963
15,2012-10-03 00:00:00,None,58,60,4,324,2,2,284.63,0.0,0.0,1,Clear,sky is clear,506
16,2012-10-03 01:00:00,None,158,59,4,324,6,6,283.47,0.0,0.0,1,Clear,sky is clear,321
17,2012-10-03 02:00:00,None,166,59,4,323,1,1,281.18,0.0,0.0,1,Clear,sky is clear,273
18,2012-10-03 03:00:00,None,101,58,4,323,7,7,281.09,0.0,0.0,1,Clear,sky is clear,367
19,2012-10-03 04:00:00,None,161,58,4,322,4,4,279.53,0.0,0.0,1,Clear,sky is clear,814
20,2012-10-03 05:00:00,None,179,57,4,322,3,3,278.62,0.0,0.0,1,Clear,sky is clear,2718
21,2012-10-03 06:00:00,None,93,57,4,322,4,4,278.23,0.0,0.0,1,Clear,sky is clear,5673
22,2012-10-03 08:00:00,None,57,56,4,321,4,4,278.12,0.0,0.0,1,Clear,sky is clear,6511
23,2012-10-03 09:00:00,None,226,56,4,321,4,4,282.48,0.0,0.0,1,Clear,sky is clear,5471
24,2012-10-03 12:00:00,None,86,55,4,320,3,3,291.97,0.0,0.0,1,Clear,sky is clear,5097
25,2012-10-03 13:00:00,None,52,55,4,320,1,1,293.23,0.0,0.0,1,Clear,sky is clear,4887
26,2012-10-03 14:00:00,None,273,55,4,320,4,4,294.31,0.0,0.0,1,Clear,sky is clear,5337
27,2012-10-03 15:00:00,None,72,55,5,350,3,3,295.17,0.0,0.0,1,Clear,sky is clear,5692
28,2012-10-03 16:00:00,None,254,55,4,320,1,1,295.13,0.0,0.0,1,Clear,sky is clear,6137
29,2012-10-03 18:00:00,None,129,55,5,330,4,4,293.66,0.0,0.0,20,Clouds,few clouds,4623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33720,2017-05-17 10:00:00,None,284,85,2,315,7,7,290.22,0.0,0.0,90,Mist,mist,4517
33721,2017-05-17 10:00:00,None,32,85,2,315,6,6,290.22,0.0,0.0,90,Drizzle,light intensity drizzle,4517
33722,2017-05-17 11:00:00,None,75,72,2,340,8,8,291.02,0.0,0.0,90,Rain,moderate rain,4666
33723,2017-05-17 12:00:00,None,95,72,2,340,9,9,291.75,0.0,0.0,90,Rain,proximity shower rain,4990
33724,2017-05-17 12:00:00,None,209,73,1,180,6,6,291.75,0.0,0.0,90,Mist,mist,4990
33725,2017-05-17 13:00:00,None,96,68,1,315,6,6,292.09,0.0,0.0,90,Rain,proximity shower rain,4789
33726,2017-05-17 13:00:00,None,236,68,3,341,1,1,292.09,0.0,0.0,90,Drizzle,light intensity drizzle,4789
33727,2017-05-17 14:00:00,None,120,68,3,341,1,1,292.62,0.0,0.0,90,Rain,proximity shower rain,5185
33728,2017-05-17 15:00:00,None,148,62,2,335,7,7,293.15,0.0,0.0,40,Rain,proximity shower rain,5590
33729,2017-05-17 16:00:00,None,244,62,1,318,5,5,292.75,0.0,0.0,90,Rain,moderate rain,6426
33730,2017-05-17 16:00:00,None,271,62,1,333,6,6,292.75,0.0,0.0,90,Mist,mist,6426
33731,2017-05-17 17:00:00,None,218,59,2,334,6,6,292.09,0.0,0.0,90,Rain,moderate rain,5763
33732,2017-05-17 17:00:00,None,237,62,2,334,4,4,292.09,0.0,0.0,90,Mist,mist,5763
33733,2017-05-17 18:00:00,None,194,69,2,334,2,2,291.35,0.0,0.0,90,Rain,moderate rain,4864
33734,2017-05-17 18:00:00,None,91,67,2,337,8,8,291.35,0.0,0.0,90,Mist,mist,4864
33735,2017-05-17 18:00:00,None,170,67,2,337,4,4,291.35,0.0,0.0,90,Drizzle,light intensity drizzle,4864
33736,2017-05-17 18:00:00,None,198,67,2,337,2,2,291.35,0.0,0.0,90,Thunderstorm,proximity thunderstorm,4864
33737,2017-05-17 19:00:00,None,27,84,1,321,4,4,290.56,0.0,0.0,90,Drizzle,light intensity drizzle,3136
33738,2017-05-17 19:00:00,None,16,84,1,321,8,8,290.56,0.0,0.0,90,Thunderstorm,proximity thunderstorm,3136
33739,2017-05-17 19:00:00,None,294,84,1,321,3,3,290.56,0.0,0.0,90,Rain,light rain,3136
33740,2017-05-17 20:00:00,None,206,86,1,326,5,5,288.89,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2733
33741,2017-05-17 20:00:00,None,232,86,1,326,6,6,288.89,0.0,0.0,90,Rain,heavy intensity rain,2733
33742,2017-05-17 20:00:00,None,83,86,1,326,1,1,288.89,0.0,0.0,90,Mist,mist,2733
33743,2017-05-17 21:00:00,None,25,85,1,328,8,8,287.88,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2348
33744,2017-05-17 21:00:00,None,269,85,1,328,5,5,287.88,0.0,0.0,90,Rain,light rain,2348
33745,2017-05-17 21:00:00,None,74,85,1,328,7,7,287.88,0.0,0.0,90,Mist,mist,2348
33746,2017-05-17 22:00:00,None,81,70,1,24,2,2,286.95,0.0,0.0,90,Rain,heavy intensity rain,2194
33747,2017-05-17 22:00:00,None,138,70,1,24,1,1,286.95,0.0,0.0,90,Mist,mist,2194
33748,2017-05-17 23:00:00,None,229,66,1,42,6,6,285.75,0.0,0.0,90,Rain,heavy intensity rain,1328
33749,2017-05-17 23:00:00,None,140,63,1,27,8,8,285.75,0.0,0.0,90,Mist,mist,1328

In [6]:
for col in test.columns:
    print('Train: '+ col+' '+ str(train[col].unique().shape))
    print('Test: '+ col+' '+ str(test[col].unique().shape))

Train: date_time (28589,)
Test: date_time (11986,)
Train: is_holiday (12,)
Test: is_holiday (12,)
Train: air_pollution_index (290,)
Test: air_pollution_index (290,)
Train: humidity (88,)
Test: humidity (91,)
Train: wind_speed (17,)
Test: wind_speed (17,)
Train: wind_direction (361,)
Test: wind_direction (356,)
Train: visibility_in_miles (9,)
Test: visibility_in_miles (9,)
Train: dew_point (9,)
Test: dew_point (9,)
Train: temperature (5611,)
Test: temperature (3334,)
Train: rain_p_h (353,)
Test: rain_p_h (87,)
Train: snow_p_h (12,)
Test: snow_p_h (1,)
Train: clouds_all (60,)
Test: clouds_all (19,)
Train: weather_type (11,)
Test: weather_type (10,)
Train: weather_description (38,)
Test: weather_description (32,)

In [7]:
for col in test.columns:
    print('Train: '+ col+' Max: '+  str(train[col].max())+' Min: '+ str(train[col].min()))
    print('Test: '+ col+' Max: '+ str(test[col].max())+' Min: '+ str(test[col].min()))

Train: date_time Max: 2017-05-17 23:00:00 Min: 2012-10-02 09:00:00
Test: date_time Max: 2018-09-30 23:00:00 Min: 2017-05-18 00:00:00
Train: is_holiday Max: Washingtons Birthday Min: Christmas Day
Test: is_holiday Max: Washingtons Birthday Min: Christmas Day
Train: air_pollution_index Max: 299 Min: 10
Test: air_pollution_index Max: 299 Min: 10
Train: humidity Max: 100 Min: 13
Test: humidity Max: 100 Min: 10
Train: wind_speed Max: 16 Min: 0
Test: wind_speed Max: 16 Min: 0
Train: wind_direction Max: 360 Min: 0
Test: wind_direction Max: 360 Min: 0
Train: visibility_in_miles Max: 9 Min: 1
Test: visibility_in_miles Max: 9 Min: 1
Train: dew_point Max: 9 Min: 1
Test: dew_point Max: 9 Min: 1
Train: temperature Max: 308.24 Min: 0.0
Test: temperature Max: 310.07 Min: 246.15
Train: rain_p_h Max: 9831.3 Min: 0.0
Test: rain_p_h Max: 10.6 Min: 0.0
Train: snow_p_h Max: 0.51 Min: 0.0
Test: snow_p_h Max: 0 Min: 0
Train: clouds_all Max: 100 Min: 0
Test: clouds_all Max: 92 Min: 0
Train: weather_type Max: Thunderstorm Min: Clear
Test: weather_type Max: Thunderstorm Min: Clear
Train: weather_description Max: very heavy rain Min: SQUALLS
Test: weather_description Max: thunderstorm with rain Min: Sky is Clear

In [8]:
train.snow_p_h.unique()

array([0.  , 0.51, 0.32, 0.06, 0.05, 0.21, 0.25, 0.44, 0.13, 0.1 , 0.17,
       0.08])

In [10]:
temp_train, temp_test = normalize(train,test,'temperature')

In [12]:
temp_test.max(), temp_train.min()

(1.0, 0.0)

In [9]:
from sklearn.preprocessing import MinMaxScaler
def normalize(train,test,label):
    sc = MinMaxScaler()
    sc.fit(pd.concat([train[label],test[label]],0).values.reshape(-1,1))
    return sc.transform(train[label].values.reshape(-1,1)), sc.transform(test[label].values.reshape(-1,1))

In [13]:
def categorize(train,test,labels,target):
    df1,df2 = train.copy(), test.copy()
    idx,_ = df1.shape
    x = pd.concat([df1.drop(target,axis=1),df2],0)
    x = pd.get_dummies(x,columns=labels,drop_first=True)
    df1 = x.iloc[:idx]
    df2 = x.iloc[idx:]
    return df1,df2

In [14]:
def rename_datetime(df1,df2):
    return df1.rename({'date_time':'ds'},inplace=True), df2.rename({'date_time':'ds'},inplace=True)

In [15]:
def prepare_dataset(train, test, index, holiday, cont_cols,target):
    df1,df2 = train.copy(), test.copy()
    for col in cont_cols:
        df1[col],df2[col] = normalize(df1,df2,col)
    x = cont_cols+ cat_cols+ [index, target]
    holidays1 = df1[df1[holiday] != 'None'][[index,holiday]]
    holidays2 = df2[df2[holiday] != 'None'][[index,holiday]]
    holidays = pd.concat([holidays1,holidays2],0)
    for col in df1.columns:
        if col not in x:
            df1 = df1.drop(col,1)
            df2 = df2.drop(col,1)
    df1,df2 = df1.rename({index:'ds'}), df2.rename({index:'ds'})
    return df1,df2,holidays

In [16]:
train.columns

Index(['date_time', 'is_holiday', 'air_pollution_index', 'humidity',
       'wind_speed', 'wind_direction', 'visibility_in_miles', 'dew_point',
       'temperature', 'rain_p_h', 'snow_p_h', 'clouds_all', 'weather_type',
       'weather_description', 'traffic_volume'],
      dtype='object')

In [19]:
cat_cols = []
for column in train.drop(['is_holiday','snow_p_h'],axis=1).columns:
    if train[column].unique().shape[0]<19:
        cat_cols.append(column)

In [20]:
cat_cols

['wind_speed', 'visibility_in_miles', 'dew_point', 'weather_type']

In [26]:
cont_cols = []
for column in train.drop(columns=['traffic_volume']).columns:
    try:
        val = int(train[column][0])
        if train[column].unique().shape[0]>=19:
            cont_cols.append(column)
    except:
        print(column)
        continue

date_time
is_holiday
weather_type
weather_description

In [27]:
cont_cols

['air_pollution_index',
 'humidity',
 'wind_direction',
 'temperature',
 'rain_p_h',
 'clouds_all']

In [31]:
cat_cols.append(['weather_description'])

(38,)

In [29]:
x = cat_cols + cont_cols
for col in train.columns:
    if col not in x:
        print(col)

date_time
is_holiday
snow_p_h
weather_description

In [154]:
training, testing, holidays = prepare_dataset(train, test, 'date_time', 'is_holiday', cont_cols, 'traffic_volume')

c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [155]:
training

,date_time,air_pollution_index,humidity,wind_direction,temperature,clouds_all
0,2012-10-02 09:00:00,0.384083,0.877778,0.913889,0.929726,0.40
1,2012-10-02 10:00:00,0.581315,0.633333,0.916667,0.933209,0.75
2,2012-10-02 11:00:00,0.356401,0.622222,0.913889,0.933918,0.90
3,2012-10-02 12:00:00,0.034602,0.622222,0.913889,0.935692,0.90
4,2012-10-02 13:00:00,0.937716,0.611111,0.913889,0.938949,0.75
5,2012-10-02 14:00:00,0.044983,0.611111,0.911111,0.940820,0.01
6,2012-10-02 15:00:00,0.602076,0.600000,0.911111,0.945496,0.01
7,2012-10-02 16:00:00,0.543253,0.600000,0.908333,0.947721,0.01
8,2012-10-02 17:00:00,0.377163,0.588889,0.908333,0.948625,0.20
9,2012-10-02 18:00:00,0.522491,0.588889,0.905556,0.945270,0.20
10,2012-10-02 19:00:00,0.806228,0.577778,0.905556,0.938401,0.20
11,2012-10-02 20:00:00,0.484429,0.577778,0.905556,0.933273,0.01
12,2012-10-02 21:00:00,0.408304,0.566667,0.902778,0.930790,0.01
13,2012-10-02 22:00:00,0.027682,0.566667,0.902778,0.926113,0.01
14,2012-10-02 23:00:00,0.608997,0.555556,0.900000,0.920599,0.01
15,2012-10-03 00:00:00,0.166090,0.555556,0.900000,0.917954,0.01
16,2012-10-03 01:00:00,0.512111,0.544444,0.900000,0.914213,0.01
17,2012-10-03 02:00:00,0.539792,0.544444,0.897222,0.906827,0.01
18,2012-10-03 03:00:00,0.314879,0.533333,0.897222,0.906537,0.01
19,2012-10-03 04:00:00,0.522491,0.533333,0.894444,0.901506,0.01
20,2012-10-03 05:00:00,0.584775,0.522222,0.894444,0.898571,0.01
21,2012-10-03 06:00:00,0.287197,0.522222,0.894444,0.897314,0.01
22,2012-10-03 08:00:00,0.162630,0.511111,0.891667,0.896959,0.01
23,2012-10-03 09:00:00,0.747405,0.511111,0.891667,0.911020,0.01
24,2012-10-03 12:00:00,0.262976,0.500000,0.888889,0.941626,0.01
25,2012-10-03 13:00:00,0.145329,0.500000,0.888889,0.945690,0.01
26,2012-10-03 14:00:00,0.910035,0.500000,0.888889,0.949173,0.01
27,2012-10-03 15:00:00,0.214533,0.500000,0.972222,0.951946,0.01
28,2012-10-03 16:00:00,0.844291,0.500000,0.888889,0.951817,0.01
29,2012-10-03 18:00:00,0.411765,0.500000,0.916667,0.947076,0.20
...,...,...,...,...,...,...
33720,2017-05-17 10:00:00,0.948097,0.833333,0.875000,0.935982,0.90
33721,2017-05-17 10:00:00,0.076125,0.833333,0.875000,0.935982,0.90
33722,2017-05-17 11:00:00,0.224913,0.688889,0.944444,0.938562,0.90
33723,2017-05-17 12:00:00,0.294118,0.688889,0.944444,0.940917,0.90
33724,2017-05-17 12:00:00,0.688581,0.700000,0.500000,0.940917,0.90
33725,2017-05-17 13:00:00,0.297578,0.644444,0.875000,0.942013,0.90
33726,2017-05-17 13:00:00,0.782007,0.644444,0.947222,0.942013,0.90
33727,2017-05-17 14:00:00,0.380623,0.644444,0.947222,0.943722,0.90
33728,2017-05-17 15:00:00,0.477509,0.577778,0.930556,0.945432,0.40
33729,2017-05-17 16:00:00,0.809689,0.577778,0.883333,0.944142,0.90
33730,2017-05-17 16:00:00,0.903114,0.577778,0.925000,0.944142,0.90
33731,2017-05-17 17:00:00,0.719723,0.544444,0.927778,0.942013,0.90
33732,2017-05-17 17:00:00,0.785467,0.577778,0.927778,0.942013,0.90
33733,2017-05-17 18:00:00,0.636678,0.655556,0.927778,0.939627,0.90
33734,2017-05-17 18:00:00,0.280277,0.633333,0.936111,0.939627,0.90
33735,2017-05-17 18:00:00,0.553633,0.633333,0.936111,0.939627,0.90
33736,2017-05-17 18:00:00,0.650519,0.633333,0.936111,0.939627,0.90
33737,2017-05-17 19:00:00,0.058824,0.822222,0.891667,0.937079,0.90
33738,2017-05-17 19:00:00,0.020761,0.822222,0.891667,0.937079,0.90
33739,2017-05-17 19:00:00,0.982699,0.822222,0.891667,0.937079,0.90
33740,2017-05-17 20:00:00,0.678201,0.844444,0.905556,0.931693,0.90
33741,2017-05-17 20:00:00,0.768166,0.844444,0.905556,0.931693,0.90
33742,2017-05-17 20:00:00,0.252595,0.844444,0.905556,0.931693,0.90
33743,2017-05-17 21:00:00,0.051903,0.833333,0.911111,0.928436,0.90
33744,2017-05-17 21:00:00,0.896194,0.833333,0.911111,0.928436,0.90
33745,2017-05-17 21:00:00,0.221453,0.833333,0.911111,0.928436,0.90
33746,2017-05-17 22:00:00,0.245675,0.666667,0.066667,0.925436,0.90
33747,2017-05-17 22:00:00,0.442907,0.666667,0.066667,0.925436,0.90
33748,2017-05-17 23:00:00,0.757785,0.622222,0.116667,0.921566,0.90
33749,2017-05-17 23:00:00,0.449827,0.588889,0.075000,0.921566,0.90

In [148]:
holidays.sort_values(by="date_time",inplace=True)

In [150]:
holidays.set_index('date_time')

                                    is_holiday
date_time
2012-10-08 00:00:00               Columbus Day
2012-11-12 00:00:00               Veterans Day
2012-11-22 00:00:00           Thanksgiving Day
2012-12-25 00:00:00              Christmas Day
2013-01-01 00:00:00              New Years Day
2013-02-18 00:00:00       Washingtons Birthday
2013-05-27 00:00:00               Memorial Day
2013-07-04 00:00:00           Independence Day
2013-08-22 00:00:00                 State Fair
2013-09-02 00:00:00                  Labor Day
2013-10-14 00:00:00               Columbus Day
2013-11-11 00:00:00               Veterans Day
2013-11-28 00:00:00           Thanksgiving Day
2013-12-25 00:00:00              Christmas Day
2014-01-01 00:00:00              New Years Day
2014-01-20 00:00:00  Martin Luther King Jr Day
2014-02-17 00:00:00       Washingtons Birthday
2014-05-26 00:00:00               Memorial Day
2015-07-03 00:00:00           Independence Day
2015-08-27 00:00:00                 State Fair
2015-09-07 00:00:00                  Labor Day
2015-10-12 00:00:00               Columbus Day
2015-11-11 00:00:00               Veterans Day
2015-11-26 00:00:00           Thanksgiving Day
2015-11-26 00:00:00           Thanksgiving Day
2015-12-25 00:00:00              Christmas Day
2016-01-01 00:00:00              New Years Day
2016-01-01 00:00:00              New Years Day
2016-02-15 00:00:00       Washingtons Birthday
2016-05-30 00:00:00               Memorial Day
...                                        ...
2016-08-25 00:00:00                 State Fair
2016-09-05 00:00:00                  Labor Day
2016-09-05 00:00:00                  Labor Day
2016-10-10 00:00:00               Columbus Day
2016-11-11 00:00:00               Veterans Day
2016-11-24 00:00:00           Thanksgiving Day
2016-12-26 00:00:00              Christmas Day
2016-12-26 00:00:00              Christmas Day
2017-01-02 00:00:00              New Years Day
2017-01-16 00:00:00  Martin Luther King Jr Day
2017-01-16 00:00:00  Martin Luther King Jr Day
2017-02-20 00:00:00       Washingtons Birthday
2017-05-29 00:00:00               Memorial Day
2017-07-04 00:00:00           Independence Day
2017-08-24 00:00:00                 State Fair
2017-09-04 00:00:00                  Labor Day
2017-10-09 00:00:00               Columbus Day
2017-11-10 00:00:00               Veterans Day
2017-11-23 00:00:00           Thanksgiving Day
2017-12-25 00:00:00              Christmas Day
2018-01-01 00:00:00              New Years Day
2018-01-15 00:00:00  Martin Luther King Jr Day
2018-01-15 00:00:00  Martin Luther King Jr Day
2018-01-15 00:00:00  Martin Luther King Jr Day
2018-02-19 00:00:00       Washingtons Birthday
2018-05-28 00:00:00               Memorial Day
2018-07-04 00:00:00           Independence Day
2018-08-23 00:00:00                 State Fair
2018-09-03 00:00:00                  Labor Day
2018-09-03 00:00:00                  Labor Day

[61 rows x 1 columns]

In [159]:
df1,df2 = train.copy(), test.copy()
idx,_ = df1.shape
x = pd.concat([df1.drop('traffic_volume',axis=1),df2],0)
x = pd.get_dummies(x,columns=cat_cols,drop_first=True)
df1 = x.rename({'date_time':'ds'}).iloc[:idx]
df2 = x.iloc[idx:]

In [164]:
df1['y'] = train['traffic_volume']
df1.head()

c:\program files\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,date_time,is_holiday,air_pollution_index,humidity,wind_direction,temperature,rain_p_h,clouds_all,weather_description,wind_speed_1,...,weather_type_Drizzle,weather_type_Fog,weather_type_Haze,weather_type_Mist,weather_type_Rain,weather_type_Smoke,weather_type_Snow,weather_type_Squall,weather_type_Thunderstorm,y
0,2012-10-02 09:00:00,None,121,89,329,288.28,0.0,40,scattered clouds,0,...,0,0,0,0,0,0,0,0,0,5545
1,2012-10-02 10:00:00,None,178,67,330,289.36,0.0,75,broken clouds,0,...,0,0,0,0,0,0,0,0,0,4516
2,2012-10-02 11:00:00,None,113,66,329,289.58,0.0,90,overcast clouds,0,...,0,0,0,0,0,0,0,0,0,4767
3,2012-10-02 12:00:00,None,20,66,329,290.13,0.0,90,overcast clouds,0,...,0,0,0,0,0,0,0,0,0,5026
4,2012-10-02 13:00:00,None,281,65,329,291.14,0.0,75,broken clouds,0,...,0,0,0,0,0,0,0,0,0,4918

In [161]:
df2

,date_time,is_holiday,air_pollution_index,humidity,wind_direction,temperature,rain_p_h,clouds_all,weather_description,wind_speed_1,...,weather_type_Clouds,weather_type_Drizzle,weather_type_Fog,weather_type_Haze,weather_type_Mist,weather_type_Rain,weather_type_Smoke,weather_type_Snow,weather_type_Squall,weather_type_Thunderstorm
0,2017-05-18 00:00:00,None,73,63,27,285.15,0.00,90,moderate rain,1,...,0,0,0,0,0,1,0,0,0,0
1,2017-05-18 00:00:00,None,251,63,27,285.15,0.00,90,mist,1,...,0,0,0,0,1,0,0,0,0,0
2,2017-05-18 00:00:00,None,75,56,0,285.15,0.00,90,light intensity drizzle,1,...,0,1,0,0,0,0,0,0,0,0
3,2017-05-18 01:00:00,None,98,56,351,284.79,0.00,90,heavy intensity rain,1,...,0,0,0,0,0,1,0,0,0,0
4,2017-05-18 01:00:00,None,283,56,351,284.79,0.00,90,mist,1,...,0,0,0,0,1,0,0,0,0,0
5,2017-05-18 02:00:00,None,115,49,27,284.29,0.00,90,heavy intensity rain,1,...,0,0,0,0,0,1,0,0,0,0
6,2017-05-18 02:00:00,None,48,49,27,284.29,0.00,90,mist,1,...,0,0,0,0,1,0,0,0,0,0
7,2017-05-18 02:00:00,None,133,49,27,284.29,0.00,90,drizzle,1,...,0,1,0,0,0,0,0,0,0,0
8,2017-05-18 03:00:00,None,130,60,36,283.51,0.00,90,heavy intensity rain,0,...,0,0,0,0,0,1,0,0,0,0
9,2017-05-18 03:00:00,None,93,60,36,283.51,0.00,90,mist,0,...,0,0,0,0,1,0,0,0,0,0
10,2017-05-18 03:00:00,None,218,60,36,283.51,0.00,90,light intensity drizzle,0,...,0,1,0,0,0,0,0,0,0,0
11,2017-05-18 04:00:00,None,272,75,78,283.09,0.00,90,heavy intensity rain,0,...,0,0,0,0,0,1,0,0,0,0
12,2017-05-18 04:00:00,None,121,75,78,283.09,0.00,90,mist,0,...,0,0,0,0,1,0,0,0,0,0
13,2017-05-18 04:00:00,None,77,75,78,283.09,0.00,90,light intensity drizzle,0,...,0,1,0,0,0,0,0,0,0,0
14,2017-05-18 05:00:00,None,231,84,93,282.55,0.00,90,moderate rain,1,...,0,0,0,0,0,1,0,0,0,0
15,2017-05-18 05:00:00,None,10,84,93,282.55,0.00,90,mist,1,...,0,0,0,0,1,0,0,0,0,0
16,2017-05-18 05:00:00,None,256,84,93,282.55,0.00,90,drizzle,1,...,0,1,0,0,0,0,0,0,0,0
17,2017-05-18 06:00:00,None,85,84,101,282.01,0.00,90,moderate rain,1,...,0,0,0,0,0,1,0,0,0,0
18,2017-05-18 06:00:00,None,89,84,101,282.01,0.00,90,heavy intensity drizzle,1,...,0,1,0,0,0,0,0,0,0,0
19,2017-05-18 07:00:00,None,165,67,169,281.77,0.00,90,moderate rain,0,...,0,0,0,0,0,1,0,0,0,0
20,2017-05-18 07:00:00,None,297,67,169,281.77,0.00,90,drizzle,0,...,0,1,0,0,0,0,0,0,0,0
21,2017-05-18 08:00:00,None,247,67,169,281.83,0.00,90,moderate rain,0,...,0,0,0,0,0,1,0,0,0,0
22,2017-05-18 08:00:00,None,28,63,175,281.83,0.00,90,light intensity drizzle,0,...,0,1,0,0,0,0,0,0,0,0
23,2017-05-18 08:00:00,None,102,51,170,281.83,0.00,90,mist,0,...,0,0,0,0,1,0,0,0,0,0
24,2017-05-18 09:00:00,None,102,51,170,282.27,0.00,90,light rain,0,...,0,0,0,0,0,1,0,0,0,0
25,2017-05-18 09:00:00,None,89,51,170,282.27,0.00,90,mist,0,...,0,0,0,0,1,0,0,0,0,0
26,2017-05-18 09:00:00,None,269,47,158,282.27,0.00,90,light intensity drizzle,1,...,0,1,0,0,0,0,0,0,0,0
27,2017-05-18 10:00:00,None,122,47,180,282.46,0.00,90,light rain,0,...,0,0,0,0,0,1,0,0,0,0
28,2017-05-18 10:00:00,None,124,47,158,282.46,0.00,90,light intensity drizzle,0,...,0,1,0,0,0,0,0,0,0,0
29,2017-05-18 11:00:00,None,181,45,183,282.95,0.00,90,light rain,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14424,2018-09-29 20:00:00,None,19,97,327,280.55,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14425,2018-09-29 21:00:00,None,251,74,168,280.40,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14426,2018-09-29 22:00:00,None,273,88,273,280.54,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14427,2018-09-29 23:00:00,None,207,97,210,280.32,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14428,2018-09-30 00:00:00,None,266,81,156,280.30,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14429,2018-09-30 01:00:00,None,290,96,187,280.19,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14430,2018-09-30 02:00:00,None,184,92,169,280.07,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14431,2018-09-30 03:00:00,None,276,10,271,280.08,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14432,2018-09-30 04:00:00,None,199,52,138,279.88,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14433,2018-09-30 05:00:00,None,224,44,219,279.96,0.00,90,overcast clouds,1,...,1,0,0,0,0,0,0,0,0,0
14434,2018-09-30 06:00:00,None,49,76,179,280.17,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14435,2018-09-30 07:00:00,None,80,67,286,280.16,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14436,2018-09-30 08:00:00,None,228,16,321,280.28,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14437,2018-09-30 09:00:00,None,14,80,208,280.62,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14438,2018-09-30 10:00:00,None,234,12,265,281.38,0.00,75,broken clouds,0,...,1,0,0,0,0,0,0,0,0,0
14439,2018-09-30 11:00:00,None,194,22,266,282.18,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14440,2018-09-30 12:00:00,None,153,14,283,282.69,0.00,75,broken clouds,0,...,1,0,0,0,0,0,0,0,0,0
14441,2018-09-30 13:00:00,None,191,10,321,283.03,0.00,90,light rain,0,...,0,0,0,0,0,1,0,0,0,0
14442,2018-09-30 14:00:00,None,225,44,344,283.48,0.00,90,light rain,0,...,0,0,0,0,0,1,0,0,0,0
14443,2018-09-30 14:00:00,None,199,86,302,283.48,0.00,90,light intensity drizzle,0,...,0,1,0,0,0,0,0,0,0,0
14444,2018-09-30 15:00:00,None,272,18,188,283.84,0.00,75,proximity shower rain,1,...,0,0,0,0,0,1,0,0,0,0
14445,2018-09-30 15:00:00,None,86,33,294,283.84,0.00,75,light intensity drizzle,0,...,0,1,0,0,0,0,0,0,0,0
14446,2018-09-30 16:00:00,None,60,71,168,284.38,0.00,75,light rain,0,...,0,0,0,0,0,1,0,0,0,0
14447,2018-09-30 17:00:00,None,133,37,346,284.79,0.00,75,broken clouds,1,...,1,0,0,0,0,0,0,0,0,0
14448,2018-09-30 18:00:00,None,133,25,227,284.20,0.25,75,light rain,0,...,0,0,0,0,0,1,0,0,0,0
14449,2018-09-30 19:00:00,None,176,21,345,283.45,0.00,75,broken clouds,0,...,1,0,0,0,0,0,0,0,0,0
14450,2018-09-30 20:00:00,None,214,95,280,282.76,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14451,2018-09-30 21:00:00,None,173,63,238,282.73,0.00,90,proximity thunderstorm,0,...,0,0,0,0,0,0,0,0,0,1
14452,2018-09-30 22:00:00,None,21,57,268,282.09,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0
14453,2018-09-30 23:00:00,None,116,70,328,282.12,0.00,90,overcast clouds,0,...,1,0,0,0,0,0,0,0,0,0

In [165]:
col_drop = ['is_holiday','rain_p_h','weather_description']
df1.drop(columns=col_drop,inplace=True)
df2.drop(columns=col_drop,inplace=True)

c:\program files\python36\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [167]:
df1.to_csv('Training.csv',index=False)
df2.to_csv('Testing.csv',index=False)
holidays.to_csv('Holidays.csv',index=False)

In [11]:
df1 = pd.read_csv('Training.csv')
df2 = pd.read_csv('Testing.csv')

In [5]:
train.columns

Index(['date_time', 'is_holiday', 'air_pollution_index', 'humidity',
       'wind_speed', 'wind_direction', 'visibility_in_miles', 'dew_point',
       'temperature', 'rain_p_h', 'snow_p_h', 'clouds_all', 'weather_type',
       'weather_description', 'traffic_volume'],
      dtype='object')

In [8]:
x = pd.concat([df1.drop('y',1), test],0)['weather_description']
x.unique().shape

(38,)

In [14]:
df1['weather_description'] = train['weather_description']
df2['weather_description'] = test['weather_description']

0        5545
1        4516
2        4767
3        5026
4        4918
5        5181
6        5584
7        6015
8        5791
9        4770
10       3539
11       2784
12       2361
13       1529
14        963
15        506
16        321
17        273
18        367
19        814
20       2718
21       5673
22       6511
23       5471
24       5097
25       4887
26       5337
27       5692
28       6137
29       4623
         ...
33720    4517
33721    4517
33722    4666
33723    4990
33724    4990
33725    4789
33726    4789
33727    5185
33728    5590
33729    6426
33730    6426
33731    5763
33732    5763
33733    4864
33734    4864
33735    4864
33736    4864
33737    3136
33738    3136
33739    3136
33740    2733
33741    2733
33742    2733
33743    2348
33744    2348
33745    2348
33746    2194
33747    2194
33748    1328
33749    1328
Name: y, Length: 33750, dtype: int64

In [17]:
history = pd.get_dummies(df1,columns=['weather_description'],drop_first=True)
future = pd.get_dummies(df2,columns=['weather_description'],drop_first=True)

In [18]:
history.to_csv('history.csv',index=False)
future.to_csv('future.csv',index=False)